// positions.js

// This file contains the layout data for all the objects in the room.
// You can modify the values here, or paste new data generated by the "Copy All" button.

const objectData = [
    { 
        name: 'Bongos',
        url: 'https://raw.githubusercontent.com/leftyskywalker/3DRoom/main/3D%20Models/bongos.glb', 
        size: 1.0, 
        pos: new THREE.Vector3(0, 0, 0), 
        rot: new THREE.Euler(0, 0, 0),
        scale: new THREE.Vector3(1, 1, 1) // Initial scale
    },
    { 
        name: 'Plant',
        url: 'https://raw.githubusercontent.com/leftyskywalker/3DRoom/main/3D%20Models/monstera_deliciosa_potted_mid-century_plant.glb', 
        size: 1.5, 
        pos: new THREE.Vector3(-4.5, 0, -4.5), 
        rot: new THREE.Euler(0, 0, 0),
        scale: new THREE.Vector3(1, 1, 1)
    },
    { 
        name: 'Piano',
        url: 'https://raw.githubusercontent.com/leftyskywalker/3DRoom/main/3D%20Models/grand_piano.glb', 
        size: 2.5, 
        pos: new THREE.Vector3(3.5, 0, 0), 
        rot: new THREE.Euler(0, -Math.PI / 2, 0),
        scale: new THREE.Vector3(1, 1, 1)
    },
    { 
        name: 'Rug',
        url: 'https://raw.githubusercontent.com/leftyskywalker/3DRoom/main/3D%20Models/rug_with_bottom.glb', 
        size: 5, 
        pos: new THREE.Vector3(0, 0.01, 0), 
        rot: new THREE.Euler(0, 0, 0),
        scale: new THREE.Vector3(1, 1, 1)
    }
];

// We need to import THREE to use Vector3 and Euler, but it will be provided by the main script.
// A simple check to avoid errors if this file is somehow run standalone.
let THREE;

export function getObjectData(threeInstance) {
    THREE = threeInstance;
    return objectData;
}