// positions.js

// This file contains the layout data for all the objects in the room.
// You can modify the values here, or paste new data generated by the "Copy All" button.
// The data is stored as plain arrays to avoid dependency issues.

const objectData = [
    { 
        name: 'Bongos',
        url: 'https://raw.githubusercontent.com/leftyskywalker/3DRoom/main/3D%20Models/bongos.glb', 
        size: 1.0, 
        pos: [0, 0, 0], 
        rot: [0, 0, 0],
        scale: [1, 1, 1]
    },
    { 
        name: 'Plant',
        url: 'https://raw.githubusercontent.com/leftyskywalker/3DRoom/main/3D%20Models/monstera_deliciosa_potted_mid-century_plant.glb', 
        size: 1.5, 
        pos: [-4.5, 0, -4.5], 
        rot: [0, 0, 0],
        scale: [1, 1, 1]
    },
    { 
        name: 'Piano',
        url: 'https://raw.githubusercontent.com/leftyskywalker/3DRoom/main/3D%20Models/grand_piano.glb', 
        size: 2.5, 
        pos: [3.5, 0, 0], 
        rot: [0, -1.57, 0], // -Math.PI / 2
        scale: [1, 1, 1]
    },
    { 
        name: 'Rug',
        url: 'https://raw.githubusercontent.com/leftyskywalker/3DRoom/main/3D%20Models/rug_with_bottom.glb', 
        size: 5, 
        pos: [0, 0.01, 0], 
        rot: [0, 0, 0],
        scale: [1, 1, 1]
    }
];

export function getObjectData() {
    return objectData;
}
